### ISSUE TITLE
some ui adjustments

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/k8s-appstore-frontend#16]
- Currently we display multiple cluster options which was required for research lab. But given we don't have any plan for that in near future, remove that option from installation page and move things up.

 - Remove "install complete" as its not really showing much. Make "Deployed" appear in yellow color and once things are running, make the text "Started/Running" and change color to green.

**Comment by paalka** [comment]
b9b16c0f197d49a93b23dd8bcc667f8f75f0e7cb and aaf877ff7df6504660ad4d275d77b4bb4e0d9347 should solve this :)
