### ISSUE TITLE
upon deletion of app, delete from dataporten as well

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/k8s-appstore-frontend#17]
When deleting app, delete it from dataporten also, as it is getting clutter in my dataporten dashboard now :)

**Comment by paalka** [comment]
Hmm, this _should_ happen automatically already.

Does this happen consistently, or only occasionally?

**Comment by gurvindersingh** [comment]
it seems to happen now and then not always. As I deleted some apps now and they are gone from my dataporten dashboard as well. Wonder if this feature was added later in the process which might explain why i have lot of apps still in dashboard.

**Comment by paalka** [comment]
That's strange, the functionality was added in around september 2017, and I haven't experienced any problems with it myself
It might be that I have deleted some of the apps manually through the Helm cli, and that the post-delete hooks haven't worked properly in that case. I'll however look into the logs and code to see if I find anything which might be buggy

**Comment by gurvindersingh** [comment]
close, as it is expected to work now
