### ISSUE TITLE
use wild-card certificate

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/k8s-appstore-frontend#19]
Currently we are using staging LE which enable us to deply multiple apps and still not hit the LE cert limit. But when we go to prod, we need to switch to LE prod issuer but then we have an issue with 20 certs per week. From this Jan, LE has started issuing wildcard cert, so I think we should have one wildcard cert per namespace and restrict users to have their host name of pattern `[a-z0-9\-].namesapce.cluster.no`. This will also means we need to update our helm charts as well. This issue will coordinate when we have [cert-manager](https://github.com/jetstack/cert-manager/) enabled in cluster rather than kube-lego, as cert-manager supports acmev2 which adds wildcard support.

**Comment by gurvindersingh** [comment]
@paalka Now i remember why i add it here. As we need to add the form validation for hostname. As mentioned in the comment above.

**Comment by paalka** [comment]
The validation should now no longer accept subdomains (i.e. foo.bar.namespace.cluster.no is no longer accepted, but bar.namespace.cluster.no still is)
