### ISSUE TITLE
add option to stop and start an application

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/k8s-appstore-frontend#20]
When a user deploy application, currently the only way to stop is to delete the app. It should be possible to stop the app, in this case the deployment resource will be deleted but name, ingress, configs, resources settings will be stored and at later stage users can either start the app or permanently delete the application.

This is to allow users to reuse the allocated resources for other application which they want to use instead of current one.

**Comment by paalka** [comment]
5f582a05366f102c15fe5f666754e3be1f531f5c adds support for this.
