### ISSUE TITLE
provide more useful information about pvc from annotations

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/k8s-appstore-frontend#21]
We should provide info about which folder is being provided with this pvc and also show once selcted where this will be mounted inside container. For PVC we will have annotation telling which volume path it is and for container mount path should be visible from pod spec.

**Comment by paalka** [comment]
Closing, as 91b8635133955d7dd5c53617779254f074641d7c adds a list of volumes to the application details page.
