### ISSUE TITLE
use endpoint status to see if deployment is ready not ingress and waiting

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/k8s-appstore-frontend#38]
Currently we wait a long time and sometime even after saying we are up, a user gets 503 as endpoint are not present. We should just check the endpoint on all the service created by that deployment and if they have endpoint listed, then our application is ready to receive traffic.

`kubectl get endpoints`

This should also speed up, as we don't need to have any random delay after this.

**Comment by paalka** [comment]
4df2112b32d0c83e88319a434db575f6c45c8a38 implements this in the frontend. The backend has been updated to support this as well.
